"""
Report exporter — generates submission-ready reports from a Finding.

Supported formats:
  markdown   → universal, readable, good for notes and Bugcrowd
  hackerone  → matches HackerOne's report field structure
  bugcrowd   → matches Bugcrowd's submission format
"""

from datetime import datetime, timezone

from src.lib.compliance import redact_headers, redact_text

# Evidence bodies are excerpted in reports; the full body stays in the DB.
_MAX_EVIDENCE_BODY = 2000


def _blank(value: str | None) -> str:
    return value.strip() if value and value.strip() else "_[not filled in]_"


def _format_exchange(ex, idx: int) -> str:
    """Render one evidence exchange as a redacted request/response block.

    Headers and bodies are scrubbed of the hunter's own secrets (cookies,
    tokens, API keys) before they go into a report that will be submitted.
    """
    headers = redact_headers(ex.request_headers or {})
    hdr_lines = "\n".join(f"{k}: {v}" for k, v in headers.items())
    req_body = (redact_text(ex.request_body) or "").strip()
    resp_excerpt = redact_text((ex.response_body or "")[:_MAX_EVIDENCE_BODY]) or ""
    label = f" — {ex.label}" if getattr(ex, "label", None) else ""

    parts = [f"**Evidence {idx}{label}**", "", "Request:", "```http", f"{ex.request_method} {ex.request_url}"]
    if hdr_lines:
        parts.append(hdr_lines)
    if req_body:
        parts.append("")
        parts.append(req_body)
    parts.append("```")
    parts.append("")
    parts.append(f"Response: `{ex.response_status}` ({ex.response_time_ms} ms)")
    parts.append("```")
    parts.append(resp_excerpt)
    parts.append("```")
    return "\n".join(parts)


def render_evidence(evidence) -> str:
    """All attached evidence exchanges as redacted request/response blocks."""
    if not evidence:
        return "_[No request/response evidence attached]_"
    return "\n\n".join(_format_exchange(ex, i) for i, ex in enumerate(evidence, 1))


def scaffold_steps(evidence) -> str:
    """Pre-fill Steps to Reproduce from the ordered evidence requests."""
    if not evidence:
        return ""
    lines = []
    for i, ex in enumerate(evidence, 1):
        label = f" ({ex.label})" if getattr(ex, "label", None) else ""
        lines.append(f"{i}. Send `{ex.request_method} {ex.request_url}`{label} → observed `{ex.response_status}`.")
    return "\n".join(lines)


def _steps(finding, evidence) -> str:
    """Use the hunter's written steps if present, else scaffold from evidence."""
    if finding.steps_to_reproduce and finding.steps_to_reproduce.strip():
        return finding.steps_to_reproduce.strip()
    scaffolded = scaffold_steps(evidence)
    return scaffolded or "_[not filled in]_"


def export_markdown(finding, program, asset, evidence=None) -> str:
    """Standard markdown report — mirrors core/report-template.md structure."""
    program_name = program.name if program else "Unknown"
    asset_value = asset.value if asset else "Unknown"
    severity = finding.severity.value.upper() if finding.severity else "UNKNOWN"
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    conf = f"{int(float(finding.confidence_score) * 100)}%" if finding.confidence_score else "unset"

    return f"""# {finding.title}

**Program:** {program_name}
**Asset:** {asset_value}
**Severity:** {severity}
**Vuln Type:** {finding.vuln_type}
**Confidence:** {conf} {f"(${finding.payout_amount})" if finding.payout_amount else ""}
**Date:** {now}

---

## Summary

{_blank(finding.summary)}

---

## Vulnerability Details

{_blank(finding.vulnerability_details)}

---

## Steps to Reproduce

{_steps(finding, evidence)}

---

## Impact

{_blank(finding.impact)}

---

## Suggested Fix

{_blank(finding.recommended_fix)}

---

## Evidence

{render_evidence(evidence)}

---

*Generated by BountyOS — review and redact before submitting*
"""


def export_hackerone(finding, program, asset, evidence=None) -> str:
    """
    HackerOne report format.
    Maps to HackerOne's submission fields:
      Title, Weakness, Severity, Summary (Vulnerability Information),
      Steps to Reproduce, Impact, Supporting Material
    """
    program_name = program.name if program else "Unknown"
    asset_value = asset.value if asset else "Unknown"
    severity = finding.severity.value.capitalize() if finding.severity else "Unknown"

    return f"""## HackerOne Report — {program_name}

### Title
{finding.title}

### Asset / URL
{asset_value}

### Weakness Type
{finding.vuln_type}

### Severity
{severity}

### Vulnerability Information (Summary)
{_blank(finding.summary)}

{_blank(finding.vulnerability_details)}

### Steps To Reproduce
{_steps(finding, evidence)}

### Impact
{_blank(finding.impact)}

### Suggested Fix (optional but recommended)
{_blank(finding.recommended_fix)}

### Supporting Material / References
{render_evidence(evidence)}

---
*Report draft generated by BountyOS — review and redact all sections before submitting*
"""


def export_bugcrowd(finding, program, asset, evidence=None) -> str:
    """
    Bugcrowd report format.
    Maps to Bugcrowd's submission fields:
      Title, Target, Bug URL, Severity, Description,
      Steps to Reproduce, Expected Result, Actual Result
    """
    program_name = program.name if program else "Unknown"
    asset_value = asset.value if asset else "Unknown"

    priority_map = {
        "critical": "P1",
        "high": "P2",
        "medium": "P3",
        "low": "P4",
        "informational": "P5",
    }
    priority = priority_map.get(finding.severity.value if finding.severity else "", "P3")

    return f"""## Bugcrowd Report — {program_name}

### Title
{finding.title}

### Target
{program_name}

### Bug URL / Affected Asset
{asset_value}

### Priority
{priority} ({finding.severity.value if finding.severity else "medium"})

### Bug Type
{finding.vuln_type}

### Description
{_blank(finding.summary)}

{_blank(finding.vulnerability_details)}

### Steps to Reproduce
{_steps(finding, evidence)}

### Expected Result
_[What should happen if the application behaved securely]_

### Actual Result
_[What actually happens — the vulnerable behavior]_

### Impact
{_blank(finding.impact)}

### Suggested Remediation
{_blank(finding.recommended_fix)}

### Evidence
{render_evidence(evidence)}

---
*Report draft generated by BountyOS — review and redact all sections before submitting*
"""
