"""
Report exporter — generates submission-ready reports from a Finding.

Supported formats:
  markdown   → universal, readable, good for notes and Bugcrowd
  hackerone  → matches HackerOne's report field structure
  bugcrowd   → matches Bugcrowd's submission format
"""

from datetime import datetime, timezone


def _blank(value: str | None) -> str:
    return value.strip() if value and value.strip() else "_[not filled in]_"


def export_markdown(finding, program, asset) -> str:
    """Standard markdown report — mirrors core/report-template.md structure."""
    program_name = program.name if program else "Unknown"
    asset_value = asset.value if asset else "Unknown"
    severity = finding.severity.value.upper() if finding.severity else "UNKNOWN"
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    return f"""# {finding.title}

**Program:** {program_name}
**Asset:** {asset_value}
**Severity:** {severity}
**Vuln Type:** {finding.vuln_type}
**Confidence:** {int(float(finding.confidence_score) * 100)}% {f"(${finding.payout_amount})" if finding.payout_amount else ""}
**Date:** {now}

---

## Summary

{_blank(finding.summary)}

---

## Vulnerability Details

{_blank(finding.vulnerability_details)}

---

## Steps to Reproduce

{_blank(finding.steps_to_reproduce)}

---

## Impact

{_blank(finding.impact)}

---

## Suggested Fix

{_blank(finding.recommended_fix)}

---

*Generated by BountyOS*
"""


def export_hackerone(finding, program, asset) -> str:
    """
    HackerOne report format.
    Maps to HackerOne's submission fields:
      Title, Weakness, Severity, Summary (Vulnerability Information),
      Steps to Reproduce, Impact, Supporting Material
    """
    program_name = program.name if program else "Unknown"
    asset_value = asset.value if asset else "Unknown"
    severity = finding.severity.value.capitalize() if finding.severity else "Unknown"

    return f"""## HackerOne Report — {program_name}

### Title
{finding.title}

### Asset / URL
{asset_value}

### Weakness Type
{finding.vuln_type}

### Severity
{severity}

### Vulnerability Information (Summary)
{_blank(finding.summary)}

{_blank(finding.vulnerability_details)}

### Steps To Reproduce
{_blank(finding.steps_to_reproduce)}

### Impact
{_blank(finding.impact)}

### Suggested Fix (optional but recommended)
{_blank(finding.recommended_fix)}

### Supporting Material / References
_[Attach screenshots, Burp exports, screen recordings here]_

---
*Report draft generated by BountyOS — review all sections before submitting*
"""


def export_bugcrowd(finding, program, asset) -> str:
    """
    Bugcrowd report format.
    Maps to Bugcrowd's submission fields:
      Title, Target, Bug URL, Severity, Description,
      Steps to Reproduce, Expected Result, Actual Result
    """
    program_name = program.name if program else "Unknown"
    asset_value = asset.value if asset else "Unknown"

    priority_map = {
        "critical": "P1",
        "high": "P2",
        "medium": "P3",
        "low": "P4",
        "informational": "P5",
    }
    priority = priority_map.get(finding.severity.value if finding.severity else "", "P3")

    return f"""## Bugcrowd Report — {program_name}

### Title
{finding.title}

### Target
{program_name}

### Bug URL / Affected Asset
{asset_value}

### Priority
{priority} ({finding.severity.value if finding.severity else "medium"})

### Bug Type
{finding.vuln_type}

### Description
{_blank(finding.summary)}

{_blank(finding.vulnerability_details)}

### Steps to Reproduce
{_blank(finding.steps_to_reproduce)}

### Expected Result
_[What should happen if the application behaved securely]_

### Actual Result
_[What actually happens — the vulnerable behavior]_

### Impact
{_blank(finding.impact)}

### Suggested Remediation
{_blank(finding.recommended_fix)}

---
*Report draft generated by BountyOS — review all sections before submitting*
"""
