"""initial schema

Revision ID: 05f7f4a9d5e6
Revises: 
Create Date: 2026-05-19 16:07:40.072531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '05f7f4a9d5e6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('scope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('out_of_scope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('max_payout', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('active', 'paused', 'archived', name='programstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('subdomain', 'ip', 'url', 'api_endpoint', 'mobile', 'other', name='assettype'), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'out_of_scope', name='assetstatus'), nullable=False),
    sa.Column('technologies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ports', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('screenshot_path', sa.String(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_new', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('program_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('payout_score', sa.Float(), nullable=False),
    sa.Column('scope_score', sa.Float(), nullable=False),
    sa.Column('competition_score', sa.Float(), nullable=False),
    sa.Column('fit_score', sa.Float(), nullable=False),
    sa.Column('momentum_score', sa.Float(), nullable=False),
    sa.Column('top_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scored_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('scoring_version', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recon_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('temporal_workflow_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('running', 'completed', 'failed', name='reconstatus'), nullable=False),
    sa.Column('triggered_by', sa.String(), nullable=False),
    sa.Column('assets_found', sa.Integer(), nullable=False),
    sa.Column('new_assets', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('seen', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('vuln_type', sa.String(), nullable=False),
    sa.Column('severity', sa.Enum('critical', 'high', 'medium', 'low', 'informational', name='severity'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', 'triaged', 'resolved', 'duplicate', 'not_applicable', 'paid', name='findingstatus'), nullable=False),
    sa.Column('report_url', sa.String(), nullable=True),
    sa.Column('payout_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('temporal_workflow_id', sa.String(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('triaged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('finding_id', sa.UUID(), nullable=True),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outcomes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('finding_id', sa.UUID(), nullable=False),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('payout_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('time_spent_hours', sa.Float(), nullable=True),
    sa.Column('lessons', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outcomes')
    op.drop_table('artifacts')
    op.drop_table('session_notes')
    op.drop_table('findings')
    op.drop_table('alerts')
    op.drop_table('recon_runs')
    op.drop_table('program_scores')
    op.drop_table('assets')
    op.drop_table('programs')
    sa.Enum(name='findingstatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='severity').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='reconstatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='assetstatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='assettype').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='programstatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
