"""add confidence_score to findings

Revision ID: 57154eda7e38
Revises: 05f7f4a9d5e6
Create Date: 2026-05-20 19:49:11.886221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57154eda7e38'
down_revision: Union[str, None] = '05f7f4a9d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('findings', sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('findings', 'confidence_score')
    # ### end Alembic commands ###
