"""add report fields to findings

Revision ID: 651e8677fdfc
Revises: 7a0cbb0b12ca
Create Date: 2026-05-25 16:28:07.471659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '651e8677fdfc'
down_revision: Union[str, None] = '7a0cbb0b12ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('findings', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('findings', sa.Column('vulnerability_details', sa.Text(), nullable=True))
    op.add_column('findings', sa.Column('steps_to_reproduce', sa.Text(), nullable=True))
    op.add_column('findings', sa.Column('impact', sa.Text(), nullable=True))
    op.add_column('findings', sa.Column('recommended_fix', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('findings', 'recommended_fix')
    op.drop_column('findings', 'impact')
    op.drop_column('findings', 'steps_to_reproduce')
    op.drop_column('findings', 'vulnerability_details')
    op.drop_column('findings', 'summary')
    # ### end Alembic commands ###
